language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t moctezuma19/react-proyect -f Dockerfile.dev .
script:
  - docker run -e CI=true moctezuma19/react-proyect npm run test